version: '2'
services:
  mongodb:
    image: mongo:4.1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Pa$$w0rd
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  
