spring:
  application:
    name: CRAWLER-WORKER
server:
  port: 8084
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000