spring:
  application:
    name: CRAWLER-WORKER
  data:
    mongodb:
      host: localhost
      database: crawler_1point3arces
server:
  port: 8084
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      maxQueueSize: 200
      queueSizeRejectionThreshold: 300
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            interruptOnTimeout: false


            