version: '3'
services:
  crawler-service:
    image: hs01:443/crawler-service:latest
    user: root
    environment:
      - OAUTH_VALUE=9a597bPpQ%2BWfCOWpN6kYdzwl%2FKiL5PyqKb40256n0Nwi6hMzqj8P1nnYQBIk%2Fqfi8dgthDLi8Yzm%2B%2FV337bkvDXeFqY
      - SALT_VALUE=V0h0TUbW
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    volumes:
      - ./wait_unit_healthy.sh:/wait_unit_healthy.sh
    entrypoint: ["./wait_unit_healthy.sh","eureka-server","8761","crawler-service-0.0.1-SNAPSHOT.jar"] 
    ports:
      - "8083:8083"
  crawler-worker:
    image: hs01:443/crawler-worker:latest
    user: root
    volumes:
      - ./wait_unit_healthy.sh:/wait_unit_healthy.sh
    entrypoint: ["./wait_unit_healthy.sh","eureka-server","8761","crawler-worker-0.0.1-SNAPSHOT.jar"]
  eureka-server:
    image: hs01:443/eureka-server:latest
    user: root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports: 
      - "8761:8761"
