version: '3'
services:
  crawler-service:
    image: axieyangb/crawler-service:latest
    ports: 
      - "8083:8083"
    environment:
      - OAUTH_VALUE=9a597bPpQ%2BWfCOWpN6kYdzwl%2FKiL5PyqKb40256n0Nwi6hMzqj8P1nnYQBIk%2Fqfi8dgthDLi8Yzm%2B%2FV337bkvDXeFqY
      - SALT_VALUE=V0h0TUbW
    depends_on:
      - eureka-server
    networks:
      - crawler-net
  crawler-crwaler:
    image: axieyangb/crawler-worker:latest
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - crawler-net
  eureka-server:
    image: axieyangb/eureka-server:latest
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - crawler-net
networks:
  crawler-net:
